wandb:
  project: digehealth
  run_name: lora_10_epochs_f1

data:
  annotation_paths:
    - /home/ubuntu/other/digehealth-poc/data/23M74M.txt # respect the same order here
    - /home/ubuntu/other/digehealth-poc/data/AS_1.txt
  audio_paths:
    - /home/ubuntu/other/digehealth-poc/data/23M74M.wav # respect the same order here
    - /home/ubuntu/other/digehealth-poc/data/AS_1.wav
train:
  hf_model_id: mharvill23/hubert-xlarge-bowel-sound-detector
  num_labels: 4
  batch_size: 16
  learning_rate: 1e-5
  num_epochs: 10
  num_workers: 4
  train_split_size: 0.8
  random_seed: 42
  device: cuda

checkpoint:
  load_checkpoint: True
  checkpoint_path: /home/ubuntu/other/digehealth-poc/outputs/checkpoints/2025-09-26_11-23-10/checkpoint_epoch20_step0.pt

output_dir: /home/ubuntu/other/digehealth-poc/outputs


lora_config:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - out_proj
    - intermediate_dense
    - output_dense
  bias: none
